### ISSUE TITLE
Crash in the projection step

### ISSUE THREAD

**Issue by cuix-github** [Shakebones/VFXEPOCH#24]
**Back trace the dump core, we have following information:**
<pre>
#0  0x00007ffff69a8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff69aa02a in __GI_abort () at abort.c:89
#2  0x00007ffff69a0bd7 in __assert_fail_base (fmt=<optimized out>, 
assertion=assertion@entry=0x450260 "i >= 0 && i <= m_yCell - 1 && j >= 0 && j <= m_xCell - 1", 
file=file@entry=0x4501f0 "/home/snow/dev/VFXEPOCH/source/utl/UTL_Grid.h", line=line@entry=263, 
function=function@entry=0x450520 <VFXEpoch::Grid2D<double>::operator()(int, int)::__PRETTY_FUNCTION__> "T& VFXEpoch::Grid2D<T>::operator()(int, int) [with T = double]") at assert.c:92
#3  0x00007ffff69a0c82 in __GI___assert_fail (
assertion=0x450260 "i >= 0 && i <= m_yCell - 1 && j >= 0 && j <= m_xCell - 1", 
file=0x4501f0 "/home/snow/dev/VFXEPOCH/source/utl/UTL_Grid.h", line=263, 
function=0x450520 <VFXEpoch::Grid2D<double>::operator()(int, int)::__PRETTY_FUNCTION__> "T& VFXEpoch::Grid2D<T>::operator()(int, int) [with T = double]") at assert.c:101
#4  0x0000000000433c8e in VFXEpoch::Grid2D<double>::operator() (this=0x7fffffffda00, <b>i=0, j=-1</b>)
at /home/snow/dev/VFXEPOCH/source/utl/UTL_Grid.h:263
#5  0x000000000043881c in VFXEpoch::Solvers::EulerGAS2D::<b>apply_gradients</b> (this=0x6ba0f0)
at /home/snow/dev/VFXEPOCH/source/fluids/euler/SIM_EulerGAS.cpp:442
#6  0x0000000000437e36 in VFXEpoch::Solvers::EulerGAS2D::project (this=0x6ba0f0)
at /home/snow/dev/VFXEPOCH/source/fluids/euler/SIM_EulerGAS.cpp:366
#7  0x00000000004362e4 in VFXEpoch::Solvers::EulerGAS2D::step (this=0x6ba0f0)
at /home/snow/dev/VFXEPOCH/source/fluids/euler/SIM_EulerGAS.cpp:128
#8  0x000000000042feb1 in timer (arg=240) at /home/snow/dev/VFXEPOCH/examples/smoke/main.cpp:212
#9  0x00007ffff75fe894 in glutMainLoopEvent () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#10 0x00007ffff75ff145 in glutMainLoop () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#11 0x000000000042de17 in VFXEpoch::Gluvi::run ()
at /home/snow/dev/VFXEPOCH/examples/Common/VisualizerHelpers.cpp:1140
#12 0x00000000004306aa in main (argc=1, argv=0x7fffffffdf28) at /home/snow/dev/VFXEPOCH/examples/smoke/main.cpp:301
<pre>

**Comment by cuix-github** [comment]
Try without weights field and using the index separately to access velocity & pressure field.
e.g for velocity: velocity[idxvel(i, j)] 
e.g for pressure: pressure[idxpressure(i, j)]

**Comment by cuix-github** [comment]
This may related to the issue : https://github.com/Shakebones/VFXEPOCH/issues/25
